/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    input usb_rx,
    input reset_button,
    input p1_button,
    input p2_button,
    output reg usb_tx,
    output reg [7:0] p1_sev,
    output reg [3:0] p1_sel,
    output reg [7:0] p2_sev,
    output reg [3:0] p2_sel,
    output reg [7:0] timer_sev,
    output reg [3:0] timer_sel,
    output reg [29:0] circle_led
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  wire [1-1:0] M_p1_btn_cond_out;
  reg [1-1:0] M_p1_btn_cond_in;
  button_conditioner_2 p1_btn_cond (
    .clk(clk),
    .in(M_p1_btn_cond_in),
    .out(M_p1_btn_cond_out)
  );
  wire [1-1:0] M_p2_btn_cond_out;
  reg [1-1:0] M_p2_btn_cond_in;
  button_conditioner_2 p2_btn_cond (
    .clk(clk),
    .in(M_p2_btn_cond_in),
    .out(M_p2_btn_cond_out)
  );
  wire [1-1:0] M_rst_btn_cond_out;
  reg [1-1:0] M_rst_btn_cond_in;
  button_conditioner_2 rst_btn_cond (
    .clk(clk),
    .in(M_rst_btn_cond_in),
    .out(M_rst_btn_cond_out)
  );
  wire [1-1:0] M_p1_btn_edge_out;
  reg [1-1:0] M_p1_btn_edge_in;
  edge_detector_3 p1_btn_edge (
    .clk(clk),
    .in(M_p1_btn_edge_in),
    .out(M_p1_btn_edge_out)
  );
  wire [1-1:0] M_p2_btn_edge_out;
  reg [1-1:0] M_p2_btn_edge_in;
  edge_detector_3 p2_btn_edge (
    .clk(clk),
    .in(M_p2_btn_edge_in),
    .out(M_p2_btn_edge_out)
  );
  wire [1-1:0] M_rst_btn_edge_out;
  reg [1-1:0] M_rst_btn_edge_in;
  edge_detector_3 rst_btn_edge (
    .clk(clk),
    .in(M_rst_btn_edge_in),
    .out(M_rst_btn_edge_out)
  );
  wire [16-1:0] M_game_beta_countdown_timer_val;
  wire [16-1:0] M_game_beta_p1_score;
  wire [16-1:0] M_game_beta_p2_score;
  wire [16-1:0] M_game_beta_circle_left;
  wire [16-1:0] M_game_beta_circle_right;
  wire [82-1:0] M_game_beta_debug__;
  reg [1-1:0] M_game_beta_p1_button;
  reg [1-1:0] M_game_beta_p2_button;
  reg [1-1:0] M_game_beta_reset_button;
  beta_1_debug_4 game_beta (
    .clk(clk),
    .rst(rst),
    .p1_button(M_game_beta_p1_button),
    .p2_button(M_game_beta_p2_button),
    .reset_button(M_game_beta_reset_button),
    .countdown_timer_val(M_game_beta_countdown_timer_val),
    .p1_score(M_game_beta_p1_score),
    .p2_score(M_game_beta_p2_score),
    .circle_left(M_game_beta_circle_left),
    .circle_right(M_game_beta_circle_right),
    .debug__(M_game_beta_debug__)
  );
  wire [4-1:0] M_p1_score_decoder_out_7segsel;
  wire [8-1:0] M_p1_score_decoder_out_7seg;
  reg [16-1:0] M_p1_score_decoder_data;
  custom_seven_seg_5 p1_score_decoder (
    .clk(clk),
    .rst(rst),
    .data(M_p1_score_decoder_data),
    .out_7segsel(M_p1_score_decoder_out_7segsel),
    .out_7seg(M_p1_score_decoder_out_7seg)
  );
  wire [4-1:0] M_p2_score_decoder_out_7segsel;
  wire [8-1:0] M_p2_score_decoder_out_7seg;
  reg [16-1:0] M_p2_score_decoder_data;
  custom_seven_seg_5 p2_score_decoder (
    .clk(clk),
    .rst(rst),
    .data(M_p2_score_decoder_data),
    .out_7segsel(M_p2_score_decoder_out_7segsel),
    .out_7seg(M_p2_score_decoder_out_7seg)
  );
  wire [4-1:0] M_timer_decoder_out_7segsel;
  wire [8-1:0] M_timer_decoder_out_7seg;
  reg [16-1:0] M_timer_decoder_data;
  custom_seven_seg_5 timer_decoder (
    .clk(clk),
    .rst(rst),
    .data(M_timer_decoder_data),
    .out_7segsel(M_timer_decoder_out_7segsel),
    .out_7seg(M_timer_decoder_out_7seg)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    circle_led = 30'h00000000;
    p1_sev = 8'h00;
    p2_sev = 8'h00;
    timer_sev = 8'h00;
    M_p1_btn_cond_in = p1_button;
    M_p2_btn_cond_in = p2_button;
    M_rst_btn_cond_in = reset_button;
    M_p1_btn_edge_in = M_p1_btn_cond_out;
    M_p2_btn_edge_in = M_p2_btn_cond_out;
    M_rst_btn_edge_in = M_rst_btn_cond_out;
    M_game_beta_p1_button = M_p1_btn_edge_out;
    M_game_beta_p2_button = M_p2_btn_edge_out;
    M_game_beta_reset_button = M_rst_btn_edge_out;
    M_p1_score_decoder_data = M_game_beta_p1_score;
    M_p2_score_decoder_data = M_game_beta_p2_score;
    M_timer_decoder_data = M_game_beta_countdown_timer_val;
    p1_sev = M_p1_score_decoder_out_7seg;
    p1_sel = M_p1_score_decoder_out_7segsel;
    p2_sev = M_p2_score_decoder_out_7seg;
    p2_sel = M_p2_score_decoder_out_7segsel;
    timer_sev = M_timer_decoder_out_7seg;
    timer_sel = M_timer_decoder_out_7segsel;
    circle_led[0+14-:15] = M_game_beta_circle_left[0+14-:15];
    circle_led[15+14-:15] = M_game_beta_circle_right[0+14-:15];
  end
  
  reg [162-1:0] M_debugger_data;
  au_debugger_6 debugger (
    .clk(clk),
    .data(M_debugger_data)
  );
  
  always @* begin
    M_debugger_data = {M_game_beta_countdown_timer_val, M_game_beta_p1_score, M_game_beta_p2_score, M_game_beta_circle_left, M_game_beta_circle_right, M_game_beta_debug__};
  end
endmodule
