/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module compare_17 (
    input z,
    input v,
    input n,
    input [2:0] alufn,
    output reg c
  );
  
  
  
  always @* begin
    c = 1'h0;
    
    case (alufn[1+1-:2])
      2'h0: begin
        c = 1'h0;
      end
      2'h2: begin
        c = n ^ v;
      end
      2'h1: begin
        c = z;
      end
      2'h3: begin
        c = (n ^ v) | z;
      end
    endcase
  end
endmodule
