/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module tester_rom_11 (
    input [4:0] address,
    output reg [59:0] testcase
  );
  
  
  
  localparam TESTADD = 120'hffff8000007fff2800000010080011;
  
  localparam TESTSUB = 120'h80007fff0100012ffffffff0100004;
  
  localparam TESTMUL = 120'hffff020002fe0000000ffff0200001;
  
  localparam TESTBOOL = 240'h555511111a55550ffff555516aaaa0ffff00001effff1ffffffff18ffff1;
  
  localparam TESTSHIFT = 300'hffff001f23ffff1ffffffff2100014ffff001f2100011ffffffff2080001ffff000f2080000;
  
  localparam TESTCOMP = 180'h555555553700014555555553500004555555553300014;
  
  localparam TESTINCR = 180'h0001ffff41000047fffffff40100030000ffff4000010;
  
  localparam TESTBOOL2 = 240'h0001ffff15000105555aaaa19000030000555511aaaa1ff00555517aaff1;
  
  localparam TESTS = 1560'h0001ffff15000105555aaaa19000030000555511aaaa1ff00555517aaff10001ffff41000047fffffff40100030000ffff4000010555555553700014555555553500004555555553300014ffff001f23ffff1ffffffff2100014ffff001f2100011ffffffff2080001ffff000f2080000555511111a55550ffff555516aaaa0ffff00001effff1ffffffff18ffff1ffff020002fe0000000ffff020000180007fff0100012ffffffff0100004ffff8000007fff2800000010080011000000000000000;
  
  always @* begin
    testcase = TESTS[(address)*60+59-:60];
  end
endmodule
