/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module custom_seven_seg_5 (
    input clk,
    input rst,
    input [15:0] data,
    output reg [3:0] out_7segsel,
    output reg [7:0] out_7seg
  );
  
  
  
  wire [8-1:0] M_seg_seg;
  wire [4-1:0] M_seg_sel;
  reg [16-1:0] M_seg_values;
  multi_seven_seg_12 seg (
    .clk(clk),
    .rst(rst),
    .values(M_seg_values),
    .seg(M_seg_seg),
    .sel(M_seg_sel)
  );
  
  reg [3:0] first_digit;
  
  reg [3:0] second_digit;
  
  reg [3:0] third_digit;
  
  reg [3:0] fourth_digit;
  
  always @* begin
    out_7segsel = M_seg_sel;
    out_7seg = M_seg_seg;
    
    case (data)
      16'hffff: begin
        M_seg_values = 16'hbc1a;
      end
      16'hf000: begin
        M_seg_values = 16'he05d;
      end
      16'hf001: begin
        M_seg_values = 16'hffff;
      end
      default: begin
        first_digit = data - (4'ha * (data / 4'ha));
        second_digit = (data - (7'h64 * (data / 7'h64))) / 4'ha;
        third_digit = (data - (10'h3e8 * (data / 10'h3e8))) / 7'h64;
        fourth_digit = (data - (14'h2710 * (data / 14'h2710))) / 10'h3e8;
        M_seg_values = {fourth_digit, third_digit, second_digit, first_digit};
      end
    endcase
  end
endmodule
