/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiplier_18 (
    input [15:0] a,
    input [15:0] b,
    output reg [15:0] p
  );
  
  
  
  reg [15:0] n0;
  reg [14:0] n1;
  reg [13:0] n2;
  reg [12:0] n3;
  reg [11:0] n4;
  reg [10:0] n5;
  reg [9:0] n6;
  reg [8:0] n7;
  reg [7:0] n8;
  reg [6:0] n9;
  reg [5:0] n10;
  reg [4:0] n11;
  reg [3:0] n12;
  reg [2:0] n13;
  reg [1:0] n14;
  reg n15;
  
  wire [(7'h78+0)-1:0] M_fa_s;
  wire [(7'h78+0)-1:0] M_fa_cout;
  reg [(7'h78+0)-1:0] M_fa_x;
  reg [(7'h78+0)-1:0] M_fa_y;
  reg [(7'h78+0)-1:0] M_fa_cin;
  
  genvar GEN_fa0;
  generate
  for (GEN_fa0=0;GEN_fa0<7'h78;GEN_fa0=GEN_fa0+1) begin: fa_gen_0
    full_adder_23 fa (
      .x(M_fa_x[GEN_fa0*(1)+(1)-1-:(1)]),
      .y(M_fa_y[GEN_fa0*(1)+(1)-1-:(1)]),
      .cin(M_fa_cin[GEN_fa0*(1)+(1)-1-:(1)]),
      .s(M_fa_s[GEN_fa0*(1)+(1)-1-:(1)]),
      .cout(M_fa_cout[GEN_fa0*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  always @* begin
    n0 = a & {5'h10{b[0+0-:1]}};
    n1 = a[0+14-:15] & {4'hf{b[1+0-:1]}};
    M_fa_x[0+14-:15] = n0[1+14-:15];
    M_fa_y[0+14-:15] = n1;
    M_fa_cin[0+0-:1] = 1'h0;
    M_fa_cin[1+13-:14] = M_fa_cout[0+13-:14];
    p[0+0-:1] = n0[0+0-:1];
    p[1+0-:1] = M_fa_s[0+0-:1];
    n2 = a[0+13-:14] & {4'he{b[2+0-:1]}};
    M_fa_x[15+13-:14] = M_fa_s[1+13-:14];
    M_fa_y[15+13-:14] = n2;
    M_fa_cin[15+0-:1] = 1'h0;
    M_fa_cin[16+12-:13] = M_fa_cout[15+12-:13];
    p[2+0-:1] = M_fa_s[15+0-:1];
    n3 = a[0+12-:13] & {4'hd{b[3+0-:1]}};
    M_fa_x[29+12-:13] = M_fa_s[16+12-:13];
    M_fa_y[29+12-:13] = n3;
    M_fa_cin[29+0-:1] = 1'h0;
    M_fa_cin[30+11-:12] = M_fa_cout[29+11-:12];
    p[3+0-:1] = M_fa_s[29+0-:1];
    n4 = a[0+11-:12] & {4'hc{b[4+0-:1]}};
    M_fa_x[42+11-:12] = M_fa_s[30+11-:12];
    M_fa_y[42+11-:12] = n4;
    M_fa_cin[42+0-:1] = 1'h0;
    M_fa_cin[43+10-:11] = M_fa_cout[42+10-:11];
    p[4+0-:1] = M_fa_s[42+0-:1];
    n5 = a[0+10-:11] & {4'hb{b[5+0-:1]}};
    M_fa_x[54+10-:11] = M_fa_s[43+10-:11];
    M_fa_y[54+10-:11] = n5;
    M_fa_cin[54+0-:1] = 1'h0;
    M_fa_cin[55+9-:10] = M_fa_cout[54+9-:10];
    p[5+0-:1] = M_fa_s[54+0-:1];
    n6 = a[0+9-:10] & {4'ha{b[6+0-:1]}};
    M_fa_x[65+9-:10] = M_fa_s[55+9-:10];
    M_fa_y[65+9-:10] = n6;
    M_fa_cin[65+0-:1] = 1'h0;
    M_fa_cin[66+8-:9] = M_fa_cout[65+8-:9];
    p[6+0-:1] = M_fa_s[65+0-:1];
    n7 = a[0+8-:9] & {4'h9{b[7+0-:1]}};
    M_fa_x[75+8-:9] = M_fa_s[66+8-:9];
    M_fa_y[75+8-:9] = n7;
    M_fa_cin[75+0-:1] = 1'h0;
    M_fa_cin[76+7-:8] = M_fa_cout[75+7-:8];
    p[7+0-:1] = M_fa_s[75+0-:1];
    n8 = a[0+7-:8] & {4'h8{b[8+0-:1]}};
    M_fa_x[84+7-:8] = M_fa_s[76+7-:8];
    M_fa_y[84+7-:8] = n8;
    M_fa_cin[84+0-:1] = 1'h0;
    M_fa_cin[85+6-:7] = M_fa_cout[84+6-:7];
    p[8+0-:1] = M_fa_s[84+0-:1];
    n9 = a[0+6-:7] & {3'h7{b[9+0-:1]}};
    M_fa_x[92+6-:7] = M_fa_s[85+6-:7];
    M_fa_y[92+6-:7] = n9;
    M_fa_cin[92+0-:1] = 1'h0;
    M_fa_cin[93+5-:6] = M_fa_cout[92+5-:6];
    p[9+0-:1] = M_fa_s[92+0-:1];
    n10 = a[0+5-:6] & {3'h6{b[10+0-:1]}};
    M_fa_x[99+5-:6] = M_fa_s[93+5-:6];
    M_fa_y[99+5-:6] = n10;
    M_fa_cin[99+0-:1] = 1'h0;
    M_fa_cin[100+4-:5] = M_fa_cout[99+4-:5];
    p[10+0-:1] = M_fa_s[99+0-:1];
    n11 = a[0+4-:5] & {3'h5{b[11+0-:1]}};
    M_fa_x[105+4-:5] = M_fa_s[101+4-:5];
    M_fa_y[105+4-:5] = n11;
    M_fa_cin[105+0-:1] = 1'h0;
    M_fa_cin[106+3-:4] = M_fa_cout[105+3-:4];
    p[11+0-:1] = M_fa_s[105+0-:1];
    n12 = a[0+3-:4] & {3'h4{b[12+0-:1]}};
    M_fa_x[110+3-:4] = M_fa_s[106+3-:4];
    M_fa_y[110+3-:4] = n12;
    M_fa_cin[110+0-:1] = 1'h0;
    M_fa_cin[111+2-:3] = M_fa_cout[110+2-:3];
    p[12+0-:1] = M_fa_s[110+0-:1];
    n13 = a[0+2-:3] & {2'h3{b[13+0-:1]}};
    M_fa_x[114+2-:3] = M_fa_s[111+2-:3];
    M_fa_y[114+2-:3] = n13;
    M_fa_cin[114+0-:1] = 1'h0;
    M_fa_cin[115+1-:2] = M_fa_cout[114+1-:2];
    p[13+0-:1] = M_fa_s[114+0-:1];
    n14 = a[0+1-:2] & {2'h2{b[14+0-:1]}};
    M_fa_x[117+1-:2] = M_fa_s[115+1-:2];
    M_fa_y[117+1-:2] = n14;
    M_fa_cin[117+0-:1] = 1'h0;
    M_fa_cin[118+0-:1] = M_fa_cout[117+0-:1];
    p[14+0-:1] = M_fa_s[118+0-:1];
    n15 = a[0+0-:1] & b[15+0-:1];
    M_fa_x[119+0-:1] = M_fa_s[118+0-:1];
    M_fa_y[119+0-:1] = n15;
    M_fa_cin[119+0-:1] = 1'h0;
    p[15+0-:1] = M_fa_s[119+0-:1];
  end
endmodule
