/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mux_2_18 (
    input s,
    input a,
    input b,
    output reg out
  );
  
  
  
  always @* begin
    
    case (s)
      1'h0: begin
        out = a;
      end
      1'h1: begin
        out = b;
      end
      default: begin
        out = a;
      end
    endcase
  end
endmodule
